# pnpm-workspace.yaml - 基本 pnpm workspace 配置
packages:
  - 'packages/**'
  - 'apps/**'
  - 'libs/**'
  - 'services/**'
  - 'examples/**'
  - '!**/node_modules/**'
  - '!**/dist/**'
  - '!**/coverage/**'
